project_id = "myazlrsfxugaevziixfh"

[functions.generate-image]
verify_jwt = false

[functions.generate-image-google]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-audio]
verify_jwt = false

[functions.describe-image]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.r2-signed-url]
verify_jwt = false
